import { useCallback, useEffect, useRef, useState } from 'react'
import { BrowserHandLandmarker } from '../lib/browserHandLandmarker'
import { isWordSign } from '../config/signs'

const API = '/api'
const SPECIAL = { SPACE: ' ', COMMA: ',', FULLSTOP: '.' }

export function useRecognition(mode) {
  const videoRef = useRef(null), landmarkerRef = useRef(null), busy = useRef(false), lastAt = useRef(0)
  const recognizer = useRef({ buffer: [], previous: null, count: 0, lastAdded: '' })
  const capture = useRef({ word: '', sentence: '', lastHand: Date.now(), wordCommitted: true, messageSent: true })
  const modeRef = useRef(mode), wordPauseRef = useRef(1.5), messagePauseRef = useRef(6)
  const [running, setRunning] = useState(false), [prediction, setPrediction] = useState('·'), [confidence, setConfidence] = useState(0), [hold, setHold] = useState(0)
  const [health, setHealth] = useState({ modelReady: true })
  const [sentence, setSentence] = useState(''), [word, setWord] = useState(''), [lastAdded, setLastAdded] = useState(''), [output, setOutput] = useState({ cleaned: '', marathi: '' })
  const [stats, setStats] = useState({ signs: 0, words: 0 }), [notice, setNotice] = useState(''), [chat, setChat] = useState([]), [reply, setReply] = useState(''), [lastReply, setLastReply] = useState({ text: '', marathi: '' })
  const [wordPause, setWordPause] = useState(1.5), [messagePause, setMessagePause] = useState(6), [facingMode, setFacingMode] = useState('user'), [canSwitchCamera, setCanSwitchCamera] = useState(false)
  useEffect(() => { capture.current.word = word; capture.current.sentence = sentence }, [word, sentence])
  useEffect(() => { modeRef.current = mode }, [mode])
  useEffect(() => { wordPauseRef.current = wordPause; messagePauseRef.current = messagePause }, [wordPause, messagePause])
  useEffect(() => { fetch(`${API}/health`).then(r => r.json()).then(setHealth).catch(() => setHealth({ modelReady: false, modelError: 'API server is not running.' })) }, [])
  useEffect(() => { navigator.mediaDevices?.enumerateDevices?.().then(d => setCanSwitchCamera(d.filter(x => x.kind === 'videoinput').length > 1)).catch(() => {}) }, [])
  const resetCapture = useCallback(() => { recognizer.current = { buffer: [], previous: null, count: 0, lastAdded: '' }; setSentence(''); setWord(''); setLastAdded(''); setOutput({ cleaned: '', marathi: '' }); setStats({ signs: 0, words: 0 }) }, [])
  const stopCamera = useCallback(() => { landmarkerRef.current?.stop(); videoRef.current?.srcObject?.getTracks().forEach(t => t.stop()); if (videoRef.current) videoRef.current.srcObject = null; setRunning(false) }, [])
  const finalizeConversation = useCallback(async raw => { try { const r = await fetch(`${API}/translate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: raw }) }); const m = await r.json(); setChat(items => [...items, { sender: 'isl', text: m.cleaned || m.text || raw, marathi: m.marathi || '', time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }]) } catch { setNotice('Could not finalize the signed message. Check the API server.') } }, [])
  const addConfirmed = useCallback(letter => { if (modeRef.current === 'conversation') { if (isWordSign(letter)) setSentence(v => v + letter + ' '); else if (!SPECIAL[letter]) setWord(v => v + letter); return } setStats(v => ({ ...v, signs: v.signs + 1 })); if (SPECIAL[letter]) { if (capture.current.word) { setSentence(v => v + capture.current.word + SPECIAL[letter] + ' '); setWord(''); setStats(v => ({ ...v, words: v.words + 1 })) } else setSentence(v => v + SPECIAL[letter] + ' ') } else setWord(v => v + letter) }, [])
  const handleFrame = useCallback(async frame => {
    if (!frame.leftPresent && !frame.rightPresent) { recognizer.current = { buffer: [], previous: null, count: 0, lastAdded: '' }; setPrediction('·'); setHold(0); setConfidence(0); const elapsed = (Date.now() - capture.current.lastHand) / 1000; if (modeRef.current === 'conversation') { if (elapsed >= wordPauseRef.current && !capture.current.wordCommitted && capture.current.word) { setSentence(v => v + capture.current.word + ' '); setWord(''); capture.current.wordCommitted = true } if (elapsed >= messagePauseRef.current && !capture.current.messageSent && capture.current.sentence.trim()) { const raw = capture.current.sentence.trim(); setSentence(''); capture.current.sentence = ''; capture.current.messageSent = true; finalizeConversation(raw) } } return }
    capture.current.lastHand = Date.now(); capture.current.wordCommitted = false; capture.current.messageSent = false
    if (busy.current || performance.now() - lastAt.current < 180) return; busy.current = true; lastAt.current = performance.now()
    try { const input = frame.rightPresent ? frame.rightRaw : frame.leftRaw; const features = [...frame.leftHand, ...frame.rightHand, Number(frame.leftPresent), Number(frame.rightPresent)]; let r = await fetch(`${API}/classify-browser-static`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ features }) }); if (!r.ok) r = await fetch(`${API}/classify-landmarks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ landmarks: Array.from(input) }) }); if (!r.ok) throw Error('Classifier unavailable'); const result = await r.json(); const rec = recognizer.current; rec.buffer = [...rec.buffer, result.prediction].slice(-5); const letter = [...rec.buffer].sort((a,b) => rec.buffer.filter(x => x === b).length - rec.buffer.filter(x => x === a).length)[0]; rec.count = letter === rec.previous ? rec.count + 1 : 0; rec.previous = letter; setPrediction(letter); setConfidence(result.confidence); setHold(Math.min(100, Math.round(rec.count / 20 * 100))); if (rec.count >= (modeRef.current === 'conversation' ? 2 : 20) && rec.lastAdded !== letter) { rec.lastAdded = letter; setLastAdded(letter); addConfirmed(letter) } } catch { setNotice('Hand landmarks are running locally, but the classifier API is unavailable.') } finally { busy.current = false }
  }, [addConfirmed, finalizeConversation])
  const startCamera = useCallback(async (requestedFacing = facingMode) => { try { stopCamera(); const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: requestedFacing }, width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); videoRef.current.srcObject = stream; await videoRef.current.play(); capture.current.lastHand = Date.now(); setFacingMode(requestedFacing); setRunning(true); setNotice(''); landmarkerRef.current ??= new BrowserHandLandmarker({ onFrame: handleFrame, onStatus: ({ state, message }) => state === 'error' && setNotice(`Browser MediaPipe error: ${message}`) }); landmarkerRef.current.start(videoRef.current) } catch (e) { setNotice(e?.name === 'NotAllowedError' ? 'Camera access is blocked. Please allow it in browser settings.' : 'Could not start the camera. Please check that a camera is available.') } }, [facingMode, handleFrame, stopCamera])
  const switchCamera = useCallback(() => startCamera(facingMode === 'user' ? 'environment' : 'user'), [facingMode, startCamera])
  const translate = useCallback(async () => { const text = `${sentence}${word}`.trim(); if (!text) return setNotice('Nothing to translate yet.'); setNotice('Translating…'); try { const r = await fetch(`${API}/translate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); setOutput(await r.json()); setNotice('') } catch { setNotice('Translation failed. Check the API server.') } }, [sentence, word])
  const sendReply = useCallback(async e => { e.preventDefault(); const text = reply.trim(); if (!text) return; setReply(''); let marathi = ''; try { marathi = (await (await fetch(`${API}/translate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) })).json()).marathi || '' } catch {} const message = { sender: 'you', text, marathi, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }; setLastReply({ text, marathi }); setChat(v => [...v, message]) }, [reply])
  useEffect(() => () => { stopCamera(); landmarkerRef.current?.destroy() }, [stopCamera])
  return { videoRef, running, health, prediction, confidence, hold, sentence, word, lastAdded, output, stats, notice, chat, reply, setReply, lastReply, wordPause, setWordPause, messagePause, setMessagePause, facingMode, canSwitchCamera, startCamera, stopCamera, switchCamera, resetCapture, translate, sendReply, clearChat: () => { setChat([]); setLastReply({ text: '', marathi: '' }); resetCapture() } }
}
